### ISSUE TITLE
Sandbox signup/login fails

### ISSUE THREAD

**Issue by agraebe** [blockstack/explorer#199] opened 2020-07-08 20:13 UTC
**Describe the bug**
Navigating to https://testnet-explorer.blockstack.org/sandbox and trying to login/signup opens a new popup that errors out:

<img width="1435" alt="Screen Shot 2020-07-08 at 1 09 13 PM" src="https://user-images.githubusercontent.com/1671228/86965471-7b4b5100-c11c-11ea-85e1-f165dd642660.png">

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome

**Comment by aulneau** [comment] 2020-07-08 20:22
This will be fixed with https://github.com/blockstack/explorer/pull/198, the issue is the explorer is using an older version of connect.

**Comment by aulneau** [comment] 2020-07-08 20:29
@agraebe can you try with this URL? https://explorer-git-feat-better-sandbox-ui.blockstackpbc1.vercel.app/sandbox

**Comment by agraebe** [comment] 2020-07-08 20:46
Working perfectly! Love the new look and feel :)

**Closed** 2020-07-28 13:57 UTC
Labels: bug
