### ISSUE TITLE
Basic transaction randomly "fails to fetch" on mocknet

### ISSUE THREAD

**Issue by timstackblock** [blockstack/explorer#158] opened 2020-05-21 15:04 UTC
**Describe the bug**
Go to the sand box click the basic transaction button, the address will be populated with an address by default. Click the submit button and you may get a 400 error in console and an error on the front end. I was able to get this issue 2 times but was also able to get a successful transaction 2 times.

Transaction ID: did not create a transaction
Address: STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6

**To Reproduce**
1. Go to 'explorer click the mocknet and then go to the sandbox
2. Click on basic transaction and click submit
3. You will see an error that say failure to fech api

**Expected behavior**

**Screenshots**
<img width="1440" alt="Screen Shot 2020-05-21 at 10 52 47 AM" src="https://user-images.githubusercontent.com/49165468/82572428-4bd38b80-9b52-11ea-9528-032a3177304e.png">

<img width="1436" alt="Screen Shot 2020-05-21 at 10 16 00 AM" src="https://user-images.githubusercontent.com/49165468/82572504-6b6ab400-9b52-11ea-9a04-d9be7bc97bef.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS 10.14.4]
 - Browser [e.g. chrome 81

**Comment by aulneau** [comment] 2020-06-30 13:57
I believe this was happening due to instability with the node/sidecar. I have not been able to reproduce this. Closing for now, but if the issue comes back, please reopen this ticket.

**Closed by aulneau** 2020-06-30 13:57 UTC
Labels: P3 bug, bug
