### ISSUE TITLE
Address that displays in sandbox is not the address associated with my connect 12 word seed phrase

### ISSUE THREAD

**Issue by timstackblock** [blockstack/explorer#173] opened 2020-05-28 17:23 UTC
**Describe the bug**
When I go to the CLI and make a new address I receive a 12 word seed phrase. Then I enter that seed phase into connect to use the sandbox, the address that is populated in the sandbox is not the address that is associated with that seed phrase

**To Reproduce**
1.Step 1 - User goes to the cli and uses blockstack make_keychain -t to make a new wallet
2.Step 2 - I get the seed phrase and an address that is associated with the seed phrase
3.Step 3 - I go to the testnet and I login to connect using the seed phrase
4.Step 4 - The sandbox populates with a stx address and that address is NOT my stx address that is associated with the 12 word seed phrase I used to login

**Expected behavior**
I was expecting my 12 word seed phrase from the CLI to work on the testnet explorer and fetch the address associated to that 12 word seedphrase. If this not the case users will be confused when logging in with connect.

My address address": "ST3Z5591N1S7J4DVZCGZ06R9R8BHT62VMKVFQ70B8

The address the explorer is using STV86VNZ1SS4CSRNZ8684A1ZK1PEMAKZX7Q4M0TX 

**Screenshots**
If applicable, add screenshots or consol.log to help explain your problem.

<img width="570" alt="Screen Shot 2020-05-28 at 1 03 08 PM" src="https://user-images.githubusercontent.com/49165468/83172745-0c72e500-a0e6-11ea-8d16-8136dfa353e2.png">
<img width="445" alt="Screen Shot 2020-05-28 at 1 25 37 PM" src="https://user-images.githubusercontent.com/49165468/83173303-d2eea980-a0e6-11ea-8813-73ef8a6c16e6.png">
<img width="1436" alt="Screen Shot 2020-05-28 at 1 03 18 PM" src="https://user-images.githubusercontent.com/49165468/83172742-0bda4e80-a0e6-11ea-8d33-0a84e25d97eb.png">

**Desktop (please complete the following information):**
 - OS: 10.14.4
 - Browser chrome 81

**Comment by aulneau** [comment] 2020-05-28 17:28
Yep, that is correct and not a bug -- eventually we will have the sandbox use the seed phrase address from connect, but that is still WIP.

**Comment by timstackblock** [comment] 2020-05-28 17:29
Sounds good, thanks 👍

**Comment by aulneau** [comment] 2020-06-02 13:58
Closing this as it's a deeper issue unrelated to the explorer.

**Closed by aulneau** 2020-06-02 13:58 UTC
Labels: P2 bug, bug
