### ISSUE TITLE
Rethink pending/confirmed display of transactions

### ISSUE THREAD

**Issue by aulneau** [blockstack/explorer#370] opened 2021-02-15 16:04 UTC
> maybe we can flip the view where "confirmed" is default and "pending" is a tab that people can go to
but in the confirmed tab we add this feature to show "new unconfirmed" transactions (say within last 30-60 mins)
that way we catch the use case where someone just broadcasted something and wants to check (it shows on top of confirmed) and the "pending" tab is there for someone to see the full list

@jasperjansz any thoughts?

**Comment by muneeb-ali** [comment] 2021-02-17 16:39
Thanks for starting the issue!

**Comment by jasperjansz** [comment] 2021-02-23 10:41
We separated the pending and confirmed transactions, because at the time the pending transactions would've overwhelmed the list.

Looking into this again, this doesn't seem to apply anymore.

Here is the list of currently pending transactions:
![image](https://user-images.githubusercontent.com/25477905/108832198-79f76780-75cb-11eb-9e55-99fbcaadc7b6.png)

Here's the list of confirmed transactions:
![image](https://user-images.githubusercontent.com/25477905/108832225-8380cf80-75cb-11eb-8eee-63e900719aeb.png)

If you put the two together in a list of 'all transactions', only one pending transaction would show in the list:
![image](https://user-images.githubusercontent.com/25477905/108832341-b5923180-75cb-11eb-8337-643d1c1e5920.png)

So here's my proposal: default tab is 'all transactions', the second tab is 'pending': https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Explorer?node-id=2386%3A2542

I think it solves the two major use cases where:
1. I've just broadcast a transaction and want to check its status, I don't have the ID -> It would be on the top of the list.
2. I'm just browsing -> The list of all transactions gives you a better impression of the network than the list of pending ones, and confirmed transactions are more useful to browse than pending ones.

@aulneau

**Comment by aulneau** [comment] 2021-02-25 14:41
> We separated the pending and confirmed transactions, because at the time the pending transactions would've overwhelmed the list.
> 
> Looking into this again, this doesn't seem to apply anymore.

I do not think this is a safe assumption to base our choices on. Randomly looking at the explorer now:

![Screen Shot 2021-02-25 at 8 35 45 AM](https://user-images.githubusercontent.com/11803153/109168810-cca85f00-7744-11eb-8103-444c234bb8ff.png)

The amount of pending txs will change over time and is never going to be guaranteed to be a certain value.

For the  "All Transactions" view:
- what if there are 20 pending transactions? 
- Is there some kind of time limit to add to cut off when to show certain pending transactions?
  - I had this before, and people got confused/concerned around their txs not showing
- On the "Transactions" page, do we show this same combo list, or have "confirmed" and "pending" tabs?

Curious what you think!

**Comment by markmhx** [comment] 2021-06-22 11:15
Should we return to this design consideration in the context of microblocks?

**Comment by markmhx** [comment] 2021-07-22 10:22
This is getting resolved by @fbwoolf in https://github.com/blockstack/explorer/pull/482

**Comment by fbwoolf** [comment] 2021-07-22 13:46
> This is getting resolved by @fbwoolf in #482

Should this be assigned to me and linked to my PR? I also think @aulneau flipped the lists in his cleanup PR.

**Comment by Eshwari007** [comment] 2021-08-03 21:03
Test passed in https://explorer-git-feat-microblocks-blockstack.vercel.app/transactions

**Closed by Eshwari007** 2021-08-03 21:03 UTC
Labels: enhancement
